rootProject.name = 'anvil'
include 'bom'
include 'bigint'
include 'util'
include 'crypto-spi'
include 'ecc-spi'
include 'ecc-secp256k1'
include 'ecc-ed25519'
include 'ecc-p256'
include 'paillier'
include 'shamir'
include 't-schnorr'
include 't-schnorr:frost-ed25519'
include 't-schnorr:frost-secp256k1'
include 't-schnorr:frost-p256'
include 't-ecdsa'
include 't-ecies'
include 'xchacha20-poly1305'

include 'zk-dlog'
include 'zk-spi'