dependencies {
    compileOnly(project(':bigint'))

    api(project(':zk-spi'))
    implementation(project(':ecc-spi'))
    implementation(project(':util'))

    testImplementation project(':ecc-secp256k1')
    testImplementation rootProject.ext.tss4jNative('linux-amd64')
    testImplementation rootProject.ext.tss4jNative('macos-aarch64')
    testImplementation rootProject.ext.tss4jNative('windows-amd64')
}
